### ISSUE TITLE
remake scheme for motor_control

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/PRJ-medtec_kit#5]
add cut to -5V track

**Comment by Aurelie-Mutschler** [comment]
former schemes : 
![bottom_view](https://cloud.githubusercontent.com/assets/10047375/24558672/42e7354c-163c-11e7-98c4-5acc43f0fb5e.png)
![front_view](https://cloud.githubusercontent.com/assets/10047375/24558673/42ebe48e-163c-11e7-8083-2d41776d209f.png)
![rp_bottom](https://cloud.githubusercontent.com/assets/10047375/24558674/42ec8be6-163c-11e7-80ef-3f202aa97658.png)
![rrp_front](https://cloud.githubusercontent.com/assets/10047375/24558675/42f0ac44-163c-11e7-895e-7c851c1fb282.png)

**Comment by jerome2echopen** [comment]
redone

**Comment by jerome2echopen** [comment]
I forgot to put the images...
![front_view](https://cloud.githubusercontent.com/assets/14290878/24698332/8b5f7a2a-19f0-11e7-8df2-66274d59180d.png)
![back_view](https://cloud.githubusercontent.com/assets/14290878/24698343/92af07a0-19f0-11e7-9b0e-07fc31a14aa0.png)
![rp_bottom_view](https://cloud.githubusercontent.com/assets/14290878/24698388/bb24f3f2-19f0-11e7-844a-1b8a3e703623.png)
![rp_top_view](https://cloud.githubusercontent.com/assets/14290878/24698393/bfdee54c-19f0-11e7-84ff-95a6990ee574.png)

**Comment by jerome2echopen** [comment]
Update for coherence with daughter board documentation:
![top_view](https://cloud.githubusercontent.com/assets/14290878/25046889/298912b6-2134-11e7-9873-95297eab5d8c.png)
![bottom_view](https://cloud.githubusercontent.com/assets/14290878/25046892/2de3c9dc-2134-11e7-8f32-78ba8e9adea6.png)

cf.: PRJ-medtec_kit/electronic/daughter_boards/DB-motor_control/DB-motor_control_v3/readme.md
